config/routes.rb
Rails.application.routes.draw do
  get 'prospects/index'
  devise_for :users, skip: [:registrations]

# Recrea las rutas de registro de Devise
   # Actúan sobre un usuario singular (el usuario que inició sesión)
   # Agregue las acciones que desee en 'only:'
   # Es útil para aplicaciones cerradas de uso interno para empresas
  resource :users,
      only: [:edit, :update, :destroy],
      controller: 'devise/registrations',
      as: :user_registration do
    get 'cancel'
  end
root to: 'prospects#index'
  resource :prospects do
    resources :comments
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :prospect
end

app/models/prospect.rb
class Prospect < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  def index
    @prospects = Prospect.all
  end
  
  def new
    @prospect = Prospect.new
  end

  def show
    @prospect = Prospect.find(params[:prospect_id]) 
  end

  def create
    @prospect = Prospect.new(prospect_params)
    @prospect.user_id = current_user.id
    if @prospect.save
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @prospect = Prospect.find(params[:prospect_id])
  end

  def update
    @prospect = Prospect.find(params[:prospect_id])
    @prospect.full_name = params[:full_name]
    @prospect.phone = params[:phone]
    @prospect.email = params[:email]
    @prospect.status = params[:status]
    @prospect.user_id = current_user.id
    if @prospect.update(prospect_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @prospect = Prospect.find(params[:prospect_id])
    @prospect.destroy
    redirect_to root_path
  end

  private

  def prospect_params
    params.require(:prospect).permit(:full_name, :phone, :email, :status) # Permitidos en el formulario
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1></h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/prospects/_form.html.erb
<div class="container p-3">
<p><%= simple_form_for prospect do |f| %>
<%= f.input :full_name, label: label_full_name %>
<%= f.input :phone, label: label_phone %>
<%= f.input :email, label: label_email %>
      <%= f.input :status, as: :radio_buttons, collection: [['Prospecto', 'Prospect'], ['Interesado', 'Interested'], ['cliente', 'customer']],
                  label: "Estatus",
                  required: true,
                  autofocus: true,
                  input_html: { autocomplete: "status" }%>
<button class="btn btn-success mt-3 mb-3" role="buttom"><%= f.button :submit, label_summit, class: "text-white" %></button>
<% end %>
 <div class="mt-3">
<button class="btn btn-secondary" role="buttom"><%= link_to 'Volver', root_path, class: "text-white" %></button>
</div>
</div>

app/views/prospects/edit.html.erb
<%= render  "form", prospect: @prospect, label_full_name: "Nombre completo", label_phone: "Teléfono", label_email: "e-mail", label_status: "Estatus", label_summit: "Editar" %>

app/views/prospects/index.html.erb
<div class="container">
<h1>Prospecto | <%= link_to 'Ingresar nuevo prospecto', new_prospects_path %> </h1>
<br>
<br>
<br>
<div>
    <table class="table table-striped">
    <thead>
    <tr>
        
        <th scope="col">Email</th>
        <th scope="col">Nombre</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Estatus</th>
        <th scope="col">Ingresado por</th>
        <th scope="col">Fecha Ingreso</th>
        <th scope="col">Conversaciones</th>
        <th scope="col">Opciones</th>
    </tr>
    </thead>
    <tbody>
    <% @prospects.each_with_index do |p, i| %>
    <tr>
        
        <td><%=p.email%></td>
        <td><%=p.full_name%></td>
        <td><%=p.phone%></td>
        <td><%=p.status%></td>
        <td><%=p.user.email%></td>
        <td><%=p.created_at%></td>
        <td><%=link_to 'Ver conversaciones', root_path(p)%></td>
        <td><%=link_to 'Editar', edit_prospects_path(:prospect_id => p.id)%> | <%=link_to 'Eliminar', prospects_path(:prospect_id => p.id), method: :delete, data: { confirm: 'Esta seguro de eliminar el prospecto?' }%></td>
        
    </tr>
    <%end%>
    </tbody>
    </table>
    </div>
</div>

app/views/prospects/new.html.erb
<%= render  "form", prospect: @prospect, label_full_name: "nombre completo", label_phone: "Teléfono", label_email: "e-mail", label_status: "Estatus", label_summit: "Crear" %>

app/views/prospects/show.html.erb
<div class="container">
  <div class="row justify-content-around">
    <div>
      <h3>Nombre: <%= @prospect.full_name %></h3>
      <h3>Teléfono: <%= @prospect.phone %></h3>
      <h3>Email: <%= @prospect.email %></h3>
      <h3>Estatus: <%= @prospect.status %></h3>
    </div>
    <div class="text-right">
      <button class="btn btn-secondary" role="buttom"><%= link_to "Volver", courses_path, class: "text-white" %></button>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>